### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by marijnschilling** [bakkenbaeck/ios-workshop#5]
I think it's nice to get some guidelines on testing, because it helps so much to feel secure about your code! 

- [ ] Unit tests integration tests
- [ ] But also about writing test-scenario's for physical testers internally at B&B
- [ ] QA guy
- [ ] Continuous integration. Do we want to use it? What do we want to check? How will we maintain it?

**Comment by elland** [comment]
- [ ] Being able to instantiate any view controller as root, for ease of testing.
